#https://game.ci/docs/github/builder
#https://trstringer.com/github-actions-create-release-upload-artifacts/
name: Automated Build
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          #- StandaloneOSX
          #- StandaloneWindows
          - StandaloneWindows64
          #- StandaloneLinux64
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      - name: Get version tag
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
      - uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: Release ${{ steps.tag_name.outputs.SOURCE_TAG }}
          tag_name: ${{ steps.tag_name.outputs.SOURCE_TAG }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Build-${{ matrix.targetPlatform }}.zip
          asset_name: RESS3D-${{ steps.tag_name.outputs.SOURCE_TAG }}.zip
          asset_content_type: application/zip